sudo: false
language: python
python:
  - "2.7"
  - "3.5"

addons:
  apt:
    packages:
      - vnc4server
      - xfonts-base

# command to install dependencies
install:
    - pip install -r requirements-dev.txt

# command to run tests
script: nosetests tests/unit
